### ISSUE TITLE
When editing the OTP, cursor does not move to the next input box if the edited value is the same as the old value

### ISSUE THREAD

**Issue by quanle1994** [dsznajder/react-native-otp-inputs#133]
When user changes the value in the OTP input, if the changed value is the same as the old one, the cursor will stay in that box and not move to the next one.
![image](https://user-images.githubusercontent.com/17548904/65654690-41f19b00-e04c-11e9-97ee-19dc7396fd7f.png)

**Comment by quanle1994** [comment]
@dsznajder Thank you so much for the prompt fixes. The non-editable pasted value bug was a blocker for me. However, this issue still exists.

In this screenshot, I entered 5 in the second box. When I select that box again and press 5, the cursor stays in that box, after the 5, and does not move to the third box.
![image](https://user-images.githubusercontent.com/17548904/66542818-3632c800-eb66-11e9-9f2a-ee8ba7230a1c.png)

**Comment by dsznajder** [comment]
@quanle1994 Yes, the problem is that `onKeyPress` event is not triggered properly on android when keyboard is not `default`. I have an idea to resolve this properly but it will need [native package](https://github.com/kevinejohn/react-native-keyevent). I will do it and test the next version. If everything will be fine, we will introduce the new version with guide how to setup.

**Comment by dsznajder** [comment]
@quanle1994 Now it's available through `react-native-otp-inputs@next`. Check migration guide :)

**Comment by erm1lov** [comment]
Where can we find this migration guide?
